# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'VideoChat' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoChat
pod 'Firebase/Firestore'
pod 'FirebaseFirestoreSwift'
pod "WebRTC"
end
